apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: money-ingress
  # No annotations needed for stripping anymore!
spec:
  rules:
  - http:
      paths:
      # # 1. Traffic starting with /api goes to Backend
      # - path: /api
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: money-backend-service
      #       port:
      #         number: 80
      # 2. Everything else goes to Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: money-frontend-service
            port:
              number: 80