package config

const (
	CATEGORY_TYPE_EXPENSE    = "EXPENSE"
	CATEGORY_TYPE_INCOME     = "INCOME"
	CATEGORY_TYPE_SAVINGS    = "SAVING"
	CATEGORY_TYPE_LOAN       = "LOAN"
	CATEGORY_TYPE_INVESTMENT = "INVEST"
	CATEGORY_TYPE_OTHER      = "OTHER"
)
